python3.7 scripts/ReactivityAssignedDSCIHeatmap.py H/assigned/RNA.ste summary.json 1.0 0
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py B/assigned/RNA.ste summary.json 1.0 0
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py I/assigned/RNA.ste summary.json 1.0 0 
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py H/assigned/RNA.ste summary.json 2.0 0
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py B/assigned/RNA.ste summary.json 2.0 0
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py I/assigned/RNA.ste summary.json 2.0 0
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py H/assigned/RNA.ste summary.json 1.0 local
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py B/assigned/RNA.ste summary.json 1.0 local
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py I/assigned/RNA.ste summary.json 1.0 local
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py H/assigned/RNA.ste summary.json 2.0 local
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py B/assigned/RNA.ste summary.json 2.0 local
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py I/assigned/RNA.ste summary.json 2.0 local
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py H/assigned/RNA.ste summary.json 1.0 distal
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py B/assigned/RNA.ste summary.json 1.0 distal
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py I/assigned/RNA.ste summary.json 1.0 distal
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py H/assigned/RNA.ste summary.json 2.0 distal
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py B/assigned/RNA.ste summary.json 2.0 distal
python3.7 scripts/ReactivityAssignedDSCIHeatmap.py I/assigned/RNA.ste summary.json 2.0 distal
