name: Testing LSC - linux
run-name: ${{ github.actor }} is checking installation and function 🚀
on: workflow_dispatch
jobs:
  Test-Install:
    runs-on: ubuntu-latest
    steps:
      - name: Environment install
        run: |
          ${CONDA}/bin/conda create -n LSC python=3.9
          source ${CONDA}/bin/activate LSC
      - uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Clone bpRNA_align
        run: |
          cd src
          git clone https://github.com/BLasher113/bpRNA_align.git
          cd ..
      - name: Environment setup
        run: |
          source ${CONDA}/bin/activate LSC
          pip install .
          pip install ViennaRNA
      - run: wget -O figsharedata.zip https://figshare.com/ndownloader/articles/27281064/versions/1
      - run: ls
      - run: unzip figsharedata.zip
      - run: rm -f data/bpRNA/* data/library/*
      - run: unzip bpRNA_data.zip -d data/bpRNA
      - run: unzip library_data.zip -d data/library
      - name: Run figure scripts
        run: |
          cd data/
          chmod +x make_AUROC_curve_fits.sh
          ./make_AUROC_curve_fits.sh
          chmod +x make_avgstemplots.sh
          ./make_avgstemplots.sh
          chmod +x make_compscore_histograms.sh
          ./make_compscore_histograms.sh
          chmod +x make_DMS_heatmaps.sh
          ./make_DMS_heatmaps.sh
          chmod +x make_folded_heatmaps.sh
          ./make_folded_heatmaps.sh
          chmod +x make_perposition_stemReacs.sh
          ./make_perposition_stemReacs.sh
          chmod +x make_stemloop_energy_scatterplots.sh
          ./make_stemloop_energy_scatterplots.sh
          chmod +x plotAUROC_balance.sh
          ./plotAUROC_balance.sh
          chmod +x RNA_types.sh
          ./RNA_types.sh
          ls figures
          cd ..
